query IndexerQuery {
  roshaan_near_feed_indexer_post_likes_aggregate(
    order_by: {post: {post_likes_aggregate: {count: desc}}}
  ) {
    nodes {
      post {
        id
        post_likes_aggregate {
          aggregate {
            count
          }
        }
      }
    }
  }
}
