query IndexerQuery {
  roshaan_near_feed_indexer_post_likes_aggregate(distinct_on: post_id) {
    nodes {
      post {
        id
        post_likes_aggregate {
          aggregate {
            count
          }
        }
      }
    }
  }
}
